spring.application.name=cda-guilds-client
spring.main.web-application-type=none
spring.shell.interactive.enabled=true
spring.shell.script.enabled=true
#spring.shell.noninteractive.primary-command=launch
